### ISSUE TITLE
ToDo list 

### ISSUE THREAD

**Issue by HechtiDerLachs** [HechtiDerLachs/Oscar.jl#2]
- [ ]  implement the plausibility checks in the several constructors of the different structs.

- [ ] Reimplement printing with short and verbose printing depending on the io context.

- [ ] Implement a constructor for affine Schemes with an explicit list of variable names as argument.
- [ ] Check and eventually correct the following: The inner constructors do not have type parameters, yet. Do we need that?
- [ ] Make the Scheme Morphism struct extend the Map type from AA
- [ ] implement reduced( X::Scheme ) to pass from a given scheme to a reduced scheme. This should also return the associated projection.
- [ ] implement the primary decomposition of a given scheme together with its various inclusions.
- [ ] Implement the smoothness test
- [ ] Implement and debug the methods for the morphisms of affine schemes (translation from ring homomorphism to fractional representation and back).
- [ ] Implement glueings and CoveredScheme

**Comment by simonbrandhorst** [comment]
More to dos 

- [ ]  make the tests pass.
- [ ] do not force the construction of the ambient_ring of the parent when constructing the ambient_ring of a child. 
- [ ] coordinate rings of affine schemes
- [ ] systematically write more tests until we have 100% coverage
